'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const C=require('../sentlog/archive-core.js');
const client=fs.readFileSync('sentlog/archive-capacity.js','utf8');
const pc=fs.readFileSync('sentlog/archive-restore-pc.js','utf8');
const records=fs.readFileSync('sentlog/record-store.js','utf8');
const loader=fs.readFileSync('sentlog/index.html','utf8');
const pcpage=fs.readFileSync('sentlog-pc/index.html','utf8');
assert(loader.includes('archive-capacity.js?v=138'));
assert(loader.includes("'v1.38'"));
assert(pcpage.includes('archive-restore-pc.js?v=138'));
assert(client.includes("contextCheck(next)"));
assert(client.includes("if(!cp||cp.status!=='archived')return;"));
assert(client.includes('const unavailable=!!cp.retired||!!cp.checking'));
assert(client.includes("control('PDF・写真を端末から外す'"));
assert(client.includes("control('この端末から案件を外す'"));
assert(client.includes("control('PCからこの端末に復旧'"));
assert(client.includes('button.disabled=disabled'));
assert(client.includes('S.archiveAtomic({writes,deleteFiles:'));
assert(client.includes("await C.matches(blob,f)"));
assert(client.includes("await C.matches(await getDBFile(f.key),f)"));
assert(records.includes('async function archiveAtomic('));
assert(records.includes('memory.get(WS)!==expectedWorkspace'));
assert(records.includes('s.get(f.key).onsuccess'));
assert(pc.includes("C.validatePack(pack,job)"));
assert(pc.includes("C.matches(stored,f)"));
assert(pc.includes("await C.hash(file)"));
assert(pc.includes("'/storage/v1/object/authenticated/'"));
assert(pc.includes("method:'DELETE'"));
assert(pc.includes("rpc('pc_cleaned'"));
assert.equal(C.maySync({status:'archived',checking:false},null),false);
assert.equal(C.maySync({status:'active',checking:false},null),true);
(async()=>{
  const blob=new Blob(['keep-original']);
  const hex=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer())),x=>x.toString(16).padStart(2,'0')).join('');
  assert(await C.matches(blob,{byte_size:blob.size,sha256:hex}));
  assert.equal(await C.matches(blob,{byte_size:blob.size,sha256:'0'.repeat(64)}),false);
  console.log('PASS v1.38: archived-only gates, atomic local scope and CRC/hash verification, PC package and temporary transfer cleanup hooks');
})().catch(e=>{console.error(e);process.exitCode=1;});