'use strict';
const assert=require('node:assert/strict');
const C=require('../sentlog/archive-core.js');
const now=Date.now();let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
const payload={project:{id:'p',name:'案件',drawings:[{id:'d',updatedAt:1}],updatedAt:1},drawings:[{meta:{id:'d',updatedAt:1},state:{currentPage:1,shapes:[{id:'s',memo:'保存すべき記録',photos:[{id:'photo'}]}]}}]};
const clone=v=>JSON.parse(JSON.stringify(v));
test('view-only state and timestamps do not change content identity',()=>{const b=clone(payload);b.project.updatedAt=2;b.drawings[0].state.currentPage=9;assert.equal(C.snapshotText(b),C.snapshotText(payload));});
test('unsent annotation changes are detected',()=>{const b=clone(payload);b.drawings[0].state.shapes[0].memo='未送信';assert.notEqual(C.snapshotText(b),C.snapshotText(payload));});
test('active project automatically synchronizes',()=>assert(C.maySync({id:'p',status:'active'},null)));
test('archived project never automatically synchronizes',()=>assert(!C.maySync({id:'p',status:'archived'},null)));
test('manual synchronization is scoped to one selected archived project',()=>{assert(C.maySync({id:'p',status:'archived'},'p'));assert(!C.maySync({id:'q',status:'active'},'p'));});
test('checking overrides even a manual request',()=>assert(!C.maySync({id:'p',status:'active',checking:true},'p')));
test('unknown control fails closed',()=>assert(!C.maySync(null,null)));
const job={id:'j',project_id:'p',revision:3,catalog_hash:'a'.repeat(64),payload,manifest:[{id:'asset',key:'background:d',byte_size:3,sha256:'b'.repeat(64)}],required_devices:[{id:'device1',name:'iPad'},{id:'device2',name:'iPhone'}],reports:{},state:'checking',expires_at:new Date(now+60000).toISOString()};
test('missing device and PC acknowledgements block archiving',()=>assert.equal(C.readiness(job,now).reasons.length,3));
const ok=clone(job);for(const d of ok.required_devices)ok.reports[d.id]={clean:true,at:new Date(now).toISOString()};ok.pc_receipt={verified_at:new Date(now).toISOString()};
test('fresh complete acknowledgements allow archiving',()=>assert(C.readiness(ok,now).ready));
test('one unsent peer prevents archiving',()=>{const j=clone(ok);j.reports.device2.clean=false;assert(!C.readiness(j,now).ready);});
test('offline stale peer prevents archiving',()=>{const j=clone(ok);j.reports.device2.at=new Date(now-91000).toISOString();assert(!C.readiness(j,now).ready);});
test('old PC receipt is not proof of a present backup',()=>{const j=clone(ok);j.pc_receipt.verified_at=new Date(now-91000).toISOString();assert(!C.readiness(j,now).ready);});
test('expired or cancelled check cannot finalize',()=>{assert(!C.readiness(ok,now+61000).ready);assert(!C.readiness({...ok,state:'cancelled'},now).ready);});
test('archive path stays inside selected root',()=>assert.deepEqual(C.receiptParts('保管\\2026\\図面.pdf','保管'),['2026','図面.pdf']));
test('absolute/mismatched/traversal/double-separator paths are rejected',()=>{for(const p of ['保管/../x','別/2026/x','保管//x','保管/C:/x'])assert.throws(()=>C.receiptParts(p,'保管'));});
const pack=C.backupPack(job,{'background:d':'files/asset'});
test('backup preserves full record and photo relationships',()=>{assert(C.validatePack(pack,job));assert.equal(pack.drawingStates.d.shapes[0].photos[0].id,'photo');});
test('wrong project or truncated backup is rejected',()=>{const p=clone(pack);p.workspace.projects[0].name='別案件';assert.throws(()=>C.validatePack(p,job));const q=clone(pack);q.files=[];assert.throws(()=>C.validatePack(q,job));});
test('changed annotation data or file digest in a backup is rejected',()=>{const p=clone(pack);p.drawingStates.d.shapes=[];assert.throws(()=>C.validatePack(p,job));const q=clone(pack);q.files[0].sha256='f'.repeat(64);assert.throws(()=>C.validatePack(q,job));});
console.log('Core checks passed: '+count);
